name:                bulletproofs
version:             0.1.0
github:              "adjoint-io/bulletproofs"
license:             Apache
maintainer:          Adjoint Inc (info@adjoint.io)
category:            Cryptography
extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bulletproofs#readme>

dependencies:
- base >= 4.7 && < 5
- protolude >= 0.2
- text
- cryptonite
- memory
- arithmoi
- containers
- linear

library:
  source-dirs: .
  exposed-modules:
    - Bulletproofs.Curve
    - Bulletproofs.Fq
    - Bulletproofs.RangeProof
    - Bulletproofs.RangeProof.Internal
    - Bulletproofs.RangeProof.Prover
    - Bulletproofs.RangeProof.Verifier

    - Bulletproofs.MultiRangeProof
    - Bulletproofs.MultiRangeProof.Prover
    - Bulletproofs.MultiRangeProof.Verifier

    - Bulletproofs.InnerProductProof
    - Bulletproofs.InnerProductProof.Internal
    - Bulletproofs.InnerProductProof.Prover
    - Bulletproofs.InnerProductProof.Verifier

    - Bulletproofs.Utils

  default-extensions:
    - OverloadedStrings
    - NoImplicitPrelude

tests:
  bulletproofs-test:
    main:                TestDriver.hs
    source-dirs:         tests
    dependencies:
      - base
      - cryptonite
      - memory
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
      - QuickCheck
      - bulletproofs
    default-extensions:
      - OverloadedStrings
      - NoImplicitPrelude
