resolver: lts-13.26
extra-deps:
  - semirings-0.4.2
  - git: https://github.com/adjoint-io/galois-field.git
    commit: 47e864bfc7249687ffce2512e61b1f003b50f62a
  - git: https://github.com/adjoint-io/poly.git
    commit: 1eb5b7a820a685de7c07576e028dee332e3382f8
