resolver: lts-13.26
extra-deps:
  - criterion-1.5.2.0
  - semirings-0.5.1
  - poly-0.3.2.0
  - git: https://github.com/adjoint-io/galois-field.git
    commit: 84cccaaae8e30de2d29a8d5c2fdc208ced80391c
  - git: https://github.com/adjoint-io/elliptic-curve.git
    commit: af279477fd92a937d02f2a2430c21e1546bad879
  - git: https://github.com/adjoint-io/galois-field.git
    commit: 9d12a14d7841c50ea64d22ad9a525bb2ddea13f7
